config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   registrations: 'registrations'  }
  resources :users , only: [:show]
  root to: 'pages#home'

  resources :clothings do
    resources :purchases, only: [ :new, :create, :show, :destroy ]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clothing.rb
class Clothing < ApplicationRecord
  belongs_to :user
  validates :description, presence: :true
  validates :age, presence: :true
  validates :price, presence: :true
  validates :gender, presence: :true
  mount_uploader :photo, PhotoUploader

  has_one :purchase, dependent: :destroy

  def owner # dono da roupa
    return self.user
  end

  def customer # comprador da roupa
    return purchase.user
  end

  def self.search(gender=nil, age=nil)
    if gender
      where(gender: gender)
    elsif age
      where(age: age)
    else
      all
    end
  end

  def up_for_sale?
    !bought
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :clothing
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"


  attr_accessor :month, :year
  after_create :send_bought_email

  def distance_price
    distance = Geocoder::Calculations.distance_between([clothing.user.longitude, clothing.user.latitude],
                                                       [user.longitude, user.latitude], :units => :km)

    if distance < 100
      return 0
    elsif 300 > distance and distance > 100
      return 10
    else
      return 50
    end
  end


  def send_bought_email
    UserMailer.bought(seller).deliver_now
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, omniauth_providers: [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :clothings, dependent: :destroy
  has_many :purchases, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :phone])
  end

end

app/controllers/clothings_controller.rb
class ClothingsController < ApplicationController
  before_action :set_clothing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new]

  def new
    @clothing = current_user.clothings.new
  end

  def create
    @clothing = current_user.clothings.new(clothing_params)

    if @clothing.save
      @clothing.bought = false
      @clothing.save
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def delete
    @clothing.destroy
  end

  def show
    @clothing = Clothing.find(params[:id])
    @seller = @clothing.user
    @user = current_user
  end

  def edit
    @clothing = Clothing.find(params[:id])
  end

  def update
    if @clothing.update(clothing_params)
      redirect_to clothing_path(@clothing)
    else
      render 'edit'
    end
  end

  def index
    # if params[:gender] == "Boy"
    #   @clothings = Clothing.where(gender: "Boy")
    # elsif @clothings.gender == "Girl"
    #   @clothings = Clothing.where(gender: "Girl")
    # else
      @clothings = Clothing.search(params[:gender], params[:age])
    #end
  end

  private

  def set_clothing
    @clothing = Clothing.find(params[:id])
  end

  def clothing_params
    params.require(:clothing).permit(:description, :age, :price, :gender, :photo, :photo_cache)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def new
    @clothing = Clothing.find(params[:clothing_id])
    @purchase = @clothing.build_purchase
    @purchase.user = current_user
    @purchase.seller_id = @clothing.user_id

    @delivery_price = @purchase.distance_price
  end

  def create
    @clothing = Clothing.find(params[:clothing_id])
    @purchase = Purchase.new(purchase_params)
    @purchase.user = current_user
    @purchase.seller = @clothing.user
    @purchase.price = @clothing.price

    clothing = @purchase.clothing

    if @purchase.save
      clothing.bought = true
      clothing.save
      #redirect_to clothing_purchase_path(@purchase.clothing_id, @purchase.id)
      redirect_to clothings_path, notice: "Compra efetuada com sucesso!"
    else
      render :new
    end

  end

  def destroy
    @purchase = Purchase.find(purchase_params[:id])
    @purchase.destroy
    redirect_to clothings_path
  end

  # Como regra,
  # se for para fazer UPDATE ou CREATE
  # use o strong parameters, ex: purchase_params

  # Se for para pegar parametros da URL,
  # em qualquer outra acao do controller,
  # usar params direto.

  def show
    @purchase = Purchase.find(params[:id])

  end

  def purchase_params
    params.require(:purchase).permit(:clothing_id, :user_id, :seller_id, :price, :delivery_price, :price)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

    def after_update_path_for(resource)
      user_path(resource)
    end

    def update_resource(resource, params)
      if current_user.provider == "facebook"
        params.delete("current_password")
        resource.update_without_password(params)
      else
        resource.update_with_password(params)
      end
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show

    @user = User.find(params[:id])
    @clothings = @user.clothings

    # 1a forma -> traz apenas o que tem

    #@purchases = Purchase.where(clothing_id: @clothings.pluck(:id))

    # 2a forma -> traz apenas o que tem

    #@purchases = []
    #@clothings.each do |clothing|
      #@purchases << clothing.purchase
    #end

    # 3a forma -> traz tb nil
    #@purchases = @clothings.map(&:purchase)
    # 3a forma upgrade -> traz apenas o que tem
    @purchases = @clothings.map(&:purchase).compact


  end


end

app/helpers/applications_helper.rb
module ApplicationsHelper
 def avatar_url
   current_user.facebook_picture_url || "http://placehold.it/30x30"
 end
end

app/helpers/clothings_helper.rb
module ClothingsHelper
  def clothing_pic(clothing)
    if clothing.photo? == false
      asset_path('boy_clothing.jpeg')
    else
      cl_image_path clothing.photo, height: 300, width: 400, crop: :fill
    end
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
    def purchase_pic(purchased_clothing)
    if purchased_clothing.photo? == false
      asset_path('boy_clothing.jpeg')
    else
      cl_image_path purchased_clothing.photo, height: 300, width: 400, crop: :fill
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clothings/_clothings.html.erb
<div class="container">
  <div class="row">
    <% clothings.each do |clothing| %>
      <div class="col-xs-12 col-sm-4">
        <div class ="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= clothing_pic(clothing)%>');">
          <div class="card-category"><h3><%=clothing.gender%></h3></div>
          <div class="card-description">
              <h2><%= clothing.age%></h2>
              <p><%=clothing.description%> </p>
          </div>
            <div class="ribbon">
            <% if clothing.bought == true %>
              <span>SOLD</span>
            <%else%>
              <span>R$ <%=clothing.price%></span>
            <%end%>
          </div>
            <% if current_user %>
              <%=link_to "", clothing_path(clothing), class:"card-link" %>
            <%else%>
              <%= link_to "Login",  new_user_session_path, class:"card-link" %>
            <%end%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/clothings/_form.html.erb
<%= simple_form_for [@user, @clothing] do |f| %>
  <%= f.input :gender, collection: ["Boy", "Girl"], prompt: "Is it a boy or a girl?" %>
  <%= f.input :price, placeholder: "Select your price (R$)" %>
  <%= f.input :age, collection: ["Baby", "Toddler"], prompt: "Is it a baby or a toddler?" %>
  <%= f.input :description, placeholder: "Describe your items (condition, size)"  %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Add/update", class: "btn btn-primary" %>
  <% if @clothing.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @clothing.errors.full_messages.each do |message| %>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/clothings/_soldclothings.html.erb
<div class="container">

<% clothings.each do |clothing| %>
  <div style="display: flex">
    <div>
    <%= link_to(clothing_path(clothing)) do %>
      <%= cl_image_tag clothing.photo.url, width: 100, height: 100, crop: :fill %>
    <% end %>

    </div>
    <div style="padding-left: 10px">
    <p>Price: R$ <%=clothing.price%> </p>
    <p><%=clothing.description%> </p>
    <p>Date: <%=clothing.created_at%> </p>
    </div>
  </div>
  <br>
  <br>
<% end %>

</div>

app/views/clothings/create.html.erb
<h1>Clothings#create</h1>
<p>Find me in app/views/clothings/create.html.erb</p>

app/views/clothings/delete.html.erb
<h1>Clothings#delete</h1>
<p>Find me in app/views/clothings/delete.html.erb</p>

app/views/clothings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Edit Clothing</h1>
        <%= render 'form' %>
        <br>
    </div>
  </div>
</div>

app/views/clothings/index.html.erb
<div class="container">
  <h1> Clothings for your kid</h1>
  <br>
  <%= link_to "Sell your clothes", new_clothing_path, class: 'btn btn-danger' %>
  <br>
  <br>
  <%= render partial: 'clothings', locals: {clothings: @clothings.select { |clothing| clothing.up_for_sale? } } %>

</div>

app/views/clothings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New Clothing</h1>
        <%= render 'form' %>
        <br>
    </div>
  </div>
</div>

app/views/clothings/show.html.erb
<center>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-s-6">
        <%= cl_image_tag @clothing.photo.url, width: 200, height: 300, crop: :fill %>
        <h4><%= @clothing.description%>, (R$ <%= @clothing.price %>) </h4>
        <% if @user == @seller %>
          <%= link_to "Edit", edit_clothing_path, class: 'btn btn-lg btn-primary' %>
        <% else %>
          <%= link_to "Check out", new_clothing_purchase_path(@clothing.id), class: 'btn btn-lg btn-primary' %>
        <%end%>
      </div>
    </div>
  </div>
  <br>
</center>

app/views/clothings/update.html.erb
<h1>Clothings#update</h1>
<p>Find me in app/views/clothings/update.html.erb</p>

app/views/dashboard/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<h1><%= @user.email %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>BuyBuyBaby</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <script src="https://use.fontawesome.com/a5a7e4e15d.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.3) 50%), url('http://www.chloeaftel.com/images/pics/582_kidspillow_v03gif.gif');">
  <div class="banner-content" class="text-left">
  <br>
  <br>
     <!-- <img src="http://res.cloudinary.com/aearamos/image/upload/v1492649290/unicornbuybuy_vjq0mc.png" width="200px" height="200px" />
     <br> -->
    <h1>Buy Buy Baby!</h1>

    <p>Shop and sell kid style.</p>
    <%= link_to "BROWSE", clothings_path, class: "btn btn-primary btn-lg"  %>
  </div>


</div>

<div class="wrapper">
  <div class="container text-center padded">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= image_tag "clothly_blue.png", size: "80x80" %>
        <h4> Sell your used baby clothes</h4>
        <p> Get money to buy new clothes for your fast growing sweety</p>
      </div>

      <div class="col-xs-12 col-sm-6">
        <%= image_tag "baby_blue.png", size: "80x80" %>
          <h4> Only the best for your little one</h4>
          <p> Get the baby clothes for your cutey for the best price</p>
      </div>
    </div>
  </div>
</div>

app/views/purchases/_new.html.erb
<div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h4>Credit Card Information</h4>

  <i style="font-size:22px" class="fa">&#xf1f0; </i>
  <i style="font-size:22px" class="fa">&#xf1f3;</i>
  <i style="font-size:22px" class="fa">&#xf1f1;</i>
  <i style="font-size:22px" class="fa">&#xf1f4;</i>



   <%= simple_form_for([@clothing, @purchase]) do |f| %>
   <%= f.input "Name on Card:", input_html: { value: "" } %>
    <%= f.input "Card Number:", input_html: { value: "" } %>
    <%= f.input "Card CVV:", input_html: { value: "" } %>
    <p>Expiration Date:</p>
    <%= f.input :month, collection: 01..12%>
    <%= f.input :year, collection: 2017..2037%>
   <% end %>


    </div>
  </div>

  <div class="text-center">
  <%= simple_form_for([@clothing, @purchase]) do |f| %>
    <%= f.input :clothing_id, as: :hidden, input_html: { value: @clothing.id} %>
    <%= f.input :user_id, as: :hidden, input_html: { value: @user_id} %>
    <%= f.input :seller_id, as: :hidden, input_html: { value: @seller_id} %>
    <%= f.input :delivery_price, as: :hidden, input_html: { value: @delivery_price} %>
    <%= f.input :price, as: :hidden, input_html: { value: @clothing.price} %>
    <%= f.submit "Place your order", class: 'btn btn-lg btn-success ' %>
  <% end %>
  </div>

app/views/purchases/new.html.erb
<br>
<br>
<div class="container">
  <div class="row">

    <div class="col-md-3 col-md-offset-2 col-xs-12">
      <center>
      <h2 class="text-center">Price: R$ <%= @clothing.price %></h2>
      <h4 class="text-center">Delivery Price: R$ <%= @delivery_price %></h4>
      <%= cl_image_tag @clothing.photo.url, width: 300, height: 350, crop: :fill%>
      <h4><%= @clothing.description %></h4>
      </center>
    </div>

   <div class="col-xs-12 col-md-7 text-center">
      <%= render 'new' %>
    </div>

  </div>
</div>
<br>
<br>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <!-- <center>
  <br>
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
  <br>
  </center> -->



  <div>
    <%= image_tag "wagon-logo.png", size: "110x50" %>
    <span>    This page has been developed during the LeWagon Fullstack Bootcamp (1 week challenge) by Livia Puppa, Pedro Almeida, Arthur Ramos and Tamara Jost</span>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">

   <h4> <img src="http://res.cloudinary.com/aearamos/image/upload/v1492649290/unicornbuybuy_vjq0mc.png" height="50px" width="50px" style="text-decoration:none" /> BuyBuyBaby</h4>

  </a>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "ALL", clothings_path, class: "navbar-wagon-item navbar-wagon-link"  %>

    <!-- Text link -->
    <%= link_to "BABY", clothings_path(age: "Baby"), class: "navbar-wagon-item navbar-wagon-link"  %>
<!--     <a href="" class="navbar-wagon-item navbar-wagon-link">BABY</a>
 -->
    <!-- Text link -->
    <%= link_to "TODDLER", clothings_path(age: "Toddler"), class: "navbar-wagon-item navbar-wagon-link"  %>
<!--     <a href="" class="navbar-wagon-item navbar-wagon-link">TODDLER</a>
 -->
    <!-- Text link -->
    <%= link_to "GIRL", clothings_path(gender: "Girl"), class: "navbar-wagon-item navbar-wagon-link"  %>
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">GIRL</a> -->

    <!-- Text link -->
    <%= link_to "BOY", clothings_path(gender: "Boy"), class: "navbar-wagon-item navbar-wagon-link"  %>

    <!-- Text link -->
<!--     <a href="" class="navbar-wagon-item navbar-wagon-link">ALL</a>
 -->
    <% if !current_user %>
        <%= link_to "Login",  new_user_session_path %>
    <% else%>
    <%end%>
    <!-- Notification link-->
    <a href="" class="navbar-wagon-item navbar-wagon-link">
      <div class="badge-container">
        <% if current_user %>
      </div>
    </a>
    <!-- Profile picture and dropdown -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag avatar_url, class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', 'data-toggle' => 'dropdown' %>
            <!-- <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"> -->
                <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                  <li><%= link_to "Profile",  user_path(current_user) %></li>
                  <li><%= link_to "Logout",  destroy_user_session_path, method: :delete %></li>
            <% else %>
          <%end%>
              </ul>
          </div>
    </div>

    <!-- Button (call-to-action) -->
      <% if current_user %>
         <%= link_to "Sell!", new_clothing_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
      <%else%>
          <%= link_to "Sell!",  new_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn"%>
      <%end%>


  </div>

  <!-- Dropdown appearing on mobile only -->
  <% if current_user %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Sell", new_clothing_path%></li>
          <li><%= link_to "All", clothings_path%></li>
          <li><%= link_to "Baby", clothings_path(age: "Baby")%></li>
          <li><%= link_to "Toddler", clothings_path(age: "Toddler")%></li>
          <li><%= link_to "Boy", clothings_path(gender: "Boy")%></li>
          <li><%= link_to "Girl", clothings_path(gender: "Girl")%></li>
          <li><%= link_to "Logout",  destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  <%end%>
</div>

app/views/users/show.html.erb
<div class="container">

<h3>Great to have you here, <%= @user.first_name %>!</h3>

<h4>Your information:</h4>

<i class="fa fa-user" aria-hidden="true"></i>: <%= @user.first_name %> <%=

@user.last_name %> //

<i class="fa fa-map-marker" aria-hidden="true"></i>: <%= @user.address %> //

<i class="fa fa-phone-square" aria-hidden="true"></i>: <%= @user.phone %> //

<i class="fa fa-envelope"></i>: <%= @user.email %>

<br>

<br>

<%= link_to "Edit", edit_user_registration_path, class: "btn btn-primary" %>

<br>

</div>

<br>

<br>

<div class="container">

<div class="tabs">

<a class="tab active" data-target="#bio">

<h4>Itens you are selling:</h4>

</a>

<a class="tab" data-target="#projects">

<h3>Itens you sold:</h3>

</a>

<a class="tab" data-target="#contact">

<h3>Itens you bought:</h3>

</a>

</div>

</div>

<div class="container text-center">

<div class="tab-content" id="bio">

<%= render partial: "clothings/clothings", locals: {clothings: @clothings.select {

|clothing| clothing.up_for_sale? } } %>

</div>

<div class="tab-content hidden" id="projects">

<%= render partial: "clothings/clothings", locals: {clothings: @clothings.select {

|clothing| clothing.bought? } } %>

</div>

<div class="tab-content hidden" id="contact">

<div class="container">

<div class="row">

<% pur = Purchase.all %>

<% purchases = pur.select { |purchase| purchase.user_id == current_user.id } %>

<% purchases.each do |purchase| %>

<%purchased_clothing = Clothing.find(purchase.clothing_id)%>

<div class="col-xs-12 col-sm-4">

<div class ="card" style="background-image: linear-gradient(rgba(0,0,0,0.3),

rgba(0,0,0,0.2)), url('<%= purchase_pic(purchased_clothing)%>');">

<div class="ribbon" id="bought">

<span>BOUGHT</span>

</div>

</div>

</div>

<% end %>

</div>

</div>

</div>

</div>